apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - image: djsidhu15/todo:latest
        name: todo-app
        env:
        - name: GITHUB_CLIENT_ID
          value: df7ef16bf2f383b7ec0c
        - name: GITHUB_CLIENT_SECRET
          value: 09f679156d3b45327f8c6cd0f51fb92aa33a6fa8
        - name: LOGIN_URI
          value: https://github.com/login/oauth/authorize
        - name: ACCESS_TOKEN_URI
          value: https://github.com/login/oauth/access_token
        - name: REDIRECT_URI
          value: http://localhost:4000/github/callback
        - name: PROFILE_URI
          value: https://api.github.com
        - name: DB_URL
          value: postgres://user_1:password_1@postgres:5432/todo?sslmode=disable
        ports:
        - containerPort: 4000